// Level definitions. This file is server-side only: the expected method, path,
// query string, body and answer for every level never reach the browser.

import { ITEM_TYPES, schemas } from './schema.js';
import { findItem, reviewsFor, averageRating, recalcChecksum } from './database.js';

const queryKeys = q => Object.keys(q);
const isPlainObject = v => v !== null && typeof v === 'object' && !Array.isArray(v);

// Compares the request the player built against what the level expects.
// Returns { ok, hint } - hints say what is wrong without giving the answer away.
function expectRequest(target, spec) {
    if (target.method !== spec.method) {
        return { ok: false, hint: `This level is not asking for a ${target.method} request.` };
    }
    if (target.path !== spec.path) {
        return { ok: false, hint: `${target.path} is not the resource this level is about. Check the documentation.` };
    }
    const used = queryKeys(target.query);
    const expected = spec.query || {};
    const expectedKeys = Object.keys(expected);
    const sameQuery = used.length === expectedKeys.length
        && expectedKeys.every(k => String(target.query[k]) === String(expected[k]));
    if (!sameQuery) {
        return {
            ok: false,
            hint: expectedKeys.length === 0
                ? 'This request does not take a query string.'
                : 'The query string is not what this level asks for.',
        };
    }
    return { ok: true };
}

function needsJsonBody(target, what) {
    if (!isPlainObject(target.body)) {
        return { ok: false, hint: `This request needs a JSON body ${what}.` };
    }
    return { ok: true };
}

export const LEVELS = [
    {
        id: 1,
        name: 'Taking Inventory',
        subtitle: 'What items do we have in this shop?',
        question: 'How many items are in the catalog?',
        answer_hint: 'a whole number',
        methods: ['GET', 'POST', 'OPTIONS'],
        show_query: false,
        show_body: false,
        task: 'Read the whole item collection, then count what came back.',
        match: target => expectRequest(target, { method: 'GET', path: '/api/items' }),
        answer: session => String(session.db.items.length),
        docs: [{
            method: 'GET',
            path: '/api/items',
            summary: 'Returns the full item collection as a JSON array.',
            details: [
                'GET only reads data, it never changes it.',
                'Answers 200 OK with the array of items.',
                'A request the current level did not ask for is refused with 403 Forbidden.',
            ],
            schema: 'item',
        }],
    },

    {
        id: 2,
        name: 'Stocking the Shelf',
        subtitle: 'A new product arrived. Put it in the catalog.',
        question: 'What id did the server assign to your new item?',
        answer_hint: 'the id from the response',
        methods: ['GET', 'POST', 'PUT', 'OPTIONS'],
        show_query: false,
        show_body: true,
        body_placeholder: '{\n  "name": "...",\n  "type": "...",\n  "price": 0,\n  "stock_count": 0\n}',
        task: 'Create one new item of your own. You already saw the shape of an item in level 1, so send those same fields - minus the ones the server fills in itself.',
        match: target => {
            const shape = expectRequest(target, { method: 'POST', path: '/api/items' });
            if (!shape.ok) return shape;
            return needsJsonBody(target, 'describing the new item');
        },
        answer: session => session.game.vars.created_item_id || null,
        docs: [{
            method: 'POST',
            path: '/api/items',
            summary: 'Creates one item from the JSON body and returns the created item.',
            details: [
                'Send every required field. id and checksum are generated by the server, so sending them is an error.',
                '201 Created on success, and the response holds the new item including its id.',
                '422 Unprocessable Entity when a field is missing, has the wrong type, or is not part of the resource.',
                '400 Bad Request when the body is not valid JSON.',
            ],
            schema: 'item',
        }],
    },

    {
        id: 3,
        name: 'Filtering by Type',
        subtitle: 'The tools aisle needs a stock check.',
        note: 'A delivery just arrived: the warehouse restocked tools that were not there in level 1. The catalog really did change.',
        question: 'What is the name of the 3rd item in the response?',
        answer_hint: 'the item name',
        methods: ['GET', 'POST', 'PUT', 'OPTIONS'],
        show_query: true,
        show_body: false,
        task: 'List only the items of type "tool", by narrowing the collection with a query parameter.',
        onEnter: session => {
            if (session.game.flags.restocked) return;
            session.game.flags.restocked = true;
            session.db.items.push(
                recalcChecksum({ id: 'itm_9001', name: 'Hydraulic Jack', type: 'tool', price: 780, stock_count: 4 }),
                recalcChecksum({ id: 'itm_9002', name: 'Impact Driver', type: 'tool', price: 365, stock_count: 9 }),
            );
        },
        match: target => expectRequest(target, { method: 'GET', path: '/api/items', query: { type: 'tool' } }),
        answer: session => {
            const tools = session.db.items.filter(i => i.type === 'tool');
            return tools[2] ? tools[2].name : null;
        },
        docs: [{
            method: 'GET',
            path: '/api/items?type=<type>',
            summary: 'A query parameter filters the collection before the server returns it.',
            details: [
                `type accepts: ${ITEM_TYPES.join(', ')}.`,
                'A query string starts with ? and every parameter is name=value, joined with &.',
                'The filtering happens on the server, so the response holds only the matching items.',
            ],
        }],
    },

    {
        id: 4,
        name: 'Replacing an Item',
        subtitle: 'The publisher sent a whole new edition of a book.',
        question: 'What is the new checksum of that item?',
        answer_hint: 'the 8 character checksum',
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'OPTIONS'],
        show_query: false,
        show_body: true,
        body_placeholder: '{\n  "name": "...",\n  "type": "...",\n  "price": 0,\n  "stock_count": 0\n}',
        task: 'Replace item itm_1003 with the new edition: name "The REST Handbook, 2nd Edition", type book, price 95, stock_count 18. PUT swaps the whole item, so send all of its fields.',
        match: target => {
            const shape = expectRequest(target, { method: 'PUT', path: '/api/items/itm_1003' });
            if (!shape.ok) return shape;
            return needsJsonBody(target, 'holding the complete replacement item');
        },
        answer: session => {
            const item = findItem(session.db, 'itm_1003');
            return item ? item.checksum : null;
        },
        docs: [
            {
                method: 'GET',
                path: '/api/items/:id',
                summary: 'Returns one item. The :id part of the path is a route parameter.',
                details: [
                    'A route parameter picks out a single resource, while a query parameter filters a collection.',
                    '200 OK with the item, or 404 Not Found when nothing carries that id.',
                ],
            },
            {
                method: 'PUT',
                path: '/api/items/:id',
                summary: 'Replaces the item at :id with the JSON body.',
                details: [
                    'PUT is a full replacement, so every required field has to be present.',
                    'The checksum is recalculated from the new values and comes back in the response.',
                    '200 OK on success, 404 Not Found for an unknown id, 422 for an invalid body.',
                ],
            },
        ],
    },

    {
        id: 5,
        name: 'One Field at a Time',
        subtitle: 'A recount found a different quantity on the shelf.',
        question: 'What is the new checksum of that item?',
        answer_hint: 'the 8 character checksum',
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'OPTIONS'],
        show_query: false,
        show_body: true,
        body_placeholder: '{\n  "value": ...\n}',
        task_of: session => {
            const id = session.game.vars.created_item_id || 'the item you created in level 2';
            return `Set stock_count to 25 on ${id}, the item you created back in level 2. Change that one field only - and mind its type, because the server checks it.`;
        },
        match: (target, session) => {
            const id = session.game.vars.created_item_id;
            if (!id) return { ok: false, hint: 'Finish level 2 first: this level patches the item you created there.' };
            const shape = expectRequest(target, { method: 'PATCH', path: `/api/items/${id}/stock_count` });
            if (!shape.ok) return shape;
            if (!isPlainObject(target.body) || !('value' in target.body)) {
                return { ok: false, hint: 'The body must be a JSON object carrying the new value under "value".' };
            }
            return { ok: true };
        },
        answer: session => {
            const item = findItem(session.db, session.game.vars.created_item_id);
            return item ? item.checksum : null;
        },
        docs: [{
            method: 'PATCH',
            path: '/api/items/:id/:field',
            summary: 'Updates a single field of one item. Body: { "value": <new value> }.',
            details: [
                'PATCH is a partial update: only the field named in the path changes, the rest is left alone.',
                'The value has to match that field\'s type in the schema, so 25 and "25" are not the same thing.',
                '200 OK with the updated item, 404 for an unknown id, 422 when the field name or the value type is wrong.',
            ],
            schema: 'item',
        }],
    },

    {
        id: 6,
        name: 'Narrowing It Down',
        subtitle: 'Accounting wants one specific book, and only that one.',
        question: 'What is the checksum of the book that has 7 units in stock?',
        answer_hint: 'the 8 character checksum',
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        show_query: true,
        show_body: false,
        task: 'Stack at least two field filters in one query string, so the server hands back only the items you care about. Pick whichever fields get you there - the point is that filters combine.',
        match: target => {
            if (target.method !== 'GET') {
                return { ok: false, hint: `This level is not asking for a ${target.method} request.` };
            }
            if (target.path !== '/api/items') {
                return { ok: false, hint: `${target.path} is not the collection this level filters.` };
            }
            const itemFields = schemas.item.fields.map(f => f.name);
            const used = queryKeys(target.query);
            const unknown = used.filter(k => !itemFields.includes(k) && k !== 'sort' && k !== 'order');
            if (unknown.length) {
                return { ok: false, hint: `${unknown.join(', ')} is not a field you can filter on.` };
            }
            const filters = used.filter(k => itemFields.includes(k));
            if (filters.length < 2) {
                return { ok: false, hint: 'This level needs at least two field filters combined in the same query string.' };
            }
            return { ok: true };
        },
        answer: session => {
            const item = session.db.items.find(i => i.type === 'book' && i.stock_count === 7);
            return item ? item.checksum : null;
        },
        docs: [{
            method: 'GET',
            path: '/api/items?<field>=<value>&<field>=<value>',
            summary: 'Any item field works as a filter, and filters combine with &.',
            details: [
                'Filters are combined with AND: an item has to match every one of them to come back.',
                'Numeric fields compare as numbers, so ?stock_count=5 and ?price=99 both work.',
                'sort=<field> together with order=asc|desc orders the result.',
                '400 Bad Request when a query parameter is not a field of the resource.',
            ],
            schema: 'item',
        }],
    },

    {
        id: 7,
        name: 'Nothing to Show',
        subtitle: 'Somewhere in this API there is a collection with nothing inside it.',
        note: 'This one is a bit of exploring. Items are not the only resource here - ask the API what else it serves, then go looking.',
        question: 'What status code did the server return?',
        answer_hint: 'a 3 digit status code',
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        show_query: false,
        show_body: false,
        task: 'Find a collection that exists but holds no data, and read what the server answers. Reading around with GET costs you nothing here.',
        accepts_status: [204],
        match: target => expectRequest(target, { method: 'GET', path: '/api/posts' }),
        answer: () => '204',
        docs: [
            {
                method: 'GET',
                path: '/api',
                summary: 'The API index: lists every collection this server serves.',
                details: [
                    'Start here when you do not know what a REST API exposes.',
                    'Each entry names a collection and the path it lives at.',
                    'The schemas page linked in the header describes the fields of each one.',
                ],
            },
            {
                method: 'Reference',
                path: 'A success does not always carry data',
                summary: '204 No Content means the request worked and there is deliberately no body.',
                details: [
                    'An empty collection still exists, so asking for it is not an error.',
                    '204 is very different from 404 Not Found, where the resource itself is missing.',
                    'A 204 response is not allowed to carry a body, so look at the status line and the headers instead.',
                ],
            },
        ],
    },

    {
        id: 8,
        name: 'What Customers Say',
        subtitle: 'Reviews belong to an item. Pull the ones for the handbook.',
        question: 'What is the average rating of that item?',
        answer_hint: 'a number with one decimal',
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        show_query: false,
        show_body: false,
        task: 'List the reviews that belong to item itm_1003. Reviews are a resource nested under the item they describe.',
        match: target => expectRequest(target, { method: 'GET', path: '/api/items/itm_1003/reviews' }),
        answer: session => {
            const average = averageRating(reviewsFor(session.db, 'itm_1003'));
            return average === null ? null : String(average);
        },
        docs: [{
            method: 'GET',
            path: '/api/items/:id/reviews',
            summary: 'Returns every review attached to one item, together with a short summary.',
            details: [
                'The nested path is the relation: these are the reviews of that one specific item.',
                'The response holds item_id, count, average_rating and the reviews array.',
                '404 Not Found when the item in the path does not exist.',
            ],
            schema: 'review',
        }],
    },

    {
        id: 9,
        name: 'Leaving a Review',
        subtitle: 'The laser level deserves an opinion.',
        question: 'What id did the server assign to your review?',
        answer_hint: 'the id from the response',
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        show_query: false,
        show_body: true,
        body_placeholder: '{\n  "author": "...",\n  "rating": 0,\n  "comment": "..."\n}',
        task: 'Add a review to item itm_1006. This one needs both halves at once: the item id in the path, and the review itself in the body.',
        match: target => {
            const shape = expectRequest(target, { method: 'POST', path: '/api/items/itm_1006/reviews' });
            if (!shape.ok) return shape;
            return needsJsonBody(target, 'describing the review');
        },
        answer: session => session.game.vars.created_review_id || null,
        docs: [{
            method: 'POST',
            path: '/api/items/:id/reviews',
            summary: 'Creates a review under the item named in the path.',
            details: [
                'item_id comes from the route parameter, so it must not be sent in the body.',
                '201 Created with the new review, including the id the server assigned.',
                '404 when the item does not exist, 422 when the review body is invalid.',
            ],
            schema: 'review',
        }],
    },

    {
        id: 10,
        name: 'Cleaning Up After Yourself',
        subtitle: 'That item you invented back in level 2 does not really belong in the catalog.',
        question: 'What confirmation code did the server return for the deletion?',
        answer_hint: 'the 6 digit code from the response',
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        show_query: false,
        show_body: false,
        task_of: session => {
            const id = session.game.vars.created_item_id || 'the item you created in level 2';
            return `Remove ${id} from the catalog - the item you created yourself in level 2. The server answers with a one time confirmation code for the deletion.`;
        },
        match: (target, session) => {
            const id = session.game.vars.created_item_id;
            if (!id) return { ok: false, hint: 'Finish level 2 first: this level removes the item you created there.' };
            return expectRequest(target, { method: 'DELETE', path: `/api/items/${id}` });
        },
        answer: session => session.game.vars.last_confirmation_code || null,
        docs: [{
            method: 'DELETE',
            path: '/api/items/:id',
            summary: 'Removes one item, along with every review that belonged to it.',
            details: [
                'The change is real: later requests will not find the item again.',
                '200 OK with a summary of what was removed, plus a fresh confirmation_code for that deletion.',
                '404 Not Found when no item carries that id.',
            ],
        }],
    },

    {
        id: 11,
        name: 'Proving It Is Gone',
        subtitle: 'Do not take our word for it. Ask the server for the item you just deleted.',
        question: 'What is the value of the "error" field in the response body?',
        answer_hint: 'the error code from the response',
        methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
        show_query: false,
        show_body: false,
        task_of: session => {
            const id = session.game.vars.created_item_id || 'the item you deleted in level 10';
            return `Ask for ${id} directly, the item you just deleted, and read the error the server sends back.`;
        },
        accepts_status: [404],
        match: (target, session) => {
            const id = session.game.vars.created_item_id;
            if (!id) return { ok: false, hint: 'Finish level 2 first: this level looks for the item you created there.' };
            return expectRequest(target, { method: 'GET', path: `/api/items/${id}` });
        },
        answer: () => 'item_not_found',
        docs: [{
            method: 'Reference',
            path: 'Status codes used by this API',
            summary: 'The status code is the first thing to read in any response.',
            details: [
                '200 OK - the request succeeded and a body follows.',
                '201 Created - a new resource was created and it is in the response.',
                '204 No Content - the request succeeded and there is deliberately no body.',
                '400 Bad Request - the request itself is malformed, e.g. broken JSON or an unknown query parameter.',
                '403 Forbidden - understood, but this is not the request the current level asks for.',
                '404 Not Found - nothing lives at that path, and the body carries an "error" code.',
                '409 Conflict - that level is already solved, so it is read only now.',
                '422 Unprocessable Entity - the shape was right but the content failed validation.',
            ],
        }],
    },
];

export const levelById = id => LEVELS.find(l => l.id === id) || null;

// Documentation is cumulative: at level N the player can read everything up to N.
export function docsUpTo(levelId) {
    return LEVELS
        .filter(l => l.id <= levelId)
        .map(l => ({ level: l.id, name: l.name, entries: l.docs }));
}

export function taskText(level, session) {
    return level.task_of ? level.task_of(session) : (level.task || null);
}
